version: '3.8'

services:
  devcontainer:
    container_name: PythonDevcontainer
    network_mode: host
    build:
      context: .
      dockerfile: devcontainer.dockerfile
    volumes:
      # Mount the local directory into the container
      - ..:/workspace:cached
      # Cache dirs with lots of files to improve devcontainer performance
      - cached-virtual_env:/workspace/.venv
      # Cache Blender installation directory to speed up setup
      - blender_cache:/workspace/blender
    command: sleep infinity # Keep the container running
    # user: root

volumes:
  cached-virtual_env:
  blender_cache:
